version: '3.8'

services:
  php:
    image: php:8.0-fpm
    container_name: my_php_app
    volumes:
      - ./php-app:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - my_network
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: my_mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: your_database_user
      MYSQL_PASSWORD: your_database_password
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - my_network

networks:
  my_network:
