services:
    www:
        build: .
        ports:
            - "80:80"
        volumes:
            - ./www:/var/www/html
        links:
            - db
        networks:
            - default
    db:
        image: 'mysql/mysql-server:8.0'
        ports:
                - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '2rD#Ua9Z^Mdy'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: 'test'
            MYSQL_USER: 'root'
            MYSQL_PASSWORD: '2rD#Ua9Z^Mdy'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - persistent: /var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - db:db
        ports:
            - 82:80
        environment:
            MYSQL_USER=root
            MYSQL_PASSWORD=
            MYSQL_ROOT_PASSWORD=2rD#Ua9Z^Mdy
volumes:
    persistent: